/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package github.j_jzk.circuitsim

import java.awt.BorderLayout
import javax.swing.JFrame
import javax.swing.JLabel

class App: JFrame("Logic Circuit Simulator") {
	init {
		setLayout(BorderLayout())
		defaultCloseOperation = JFrame.EXIT_ON_CLOSE
		setSize(800, 600)
		
		val statusBar = JLabel("")
		val vp = Viewport(statusBar)
		add(vp, BorderLayout.CENTER)
		add(Toolbar(vp), BorderLayout.LINE_END)
		add(statusBar, BorderLayout.PAGE_END)
		
		pack()
		
		setVisible(true)
	}
}

fun main(args: Array<String>) {
    App()
}
