/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package github.j_jzk.circuitsim

import java.awt.BorderLayout
import javax.swing.JFrame

class App: JFrame("Logic Circuit Simulator") {
	init {
		setLayout(BorderLayout())
		defaultCloseOperation = JFrame.EXIT_ON_CLOSE
		setSize(800, 600)
		
		add(Viewport(), BorderLayout.CENTER)
		pack()
		
		setVisible(true)
	}
}

fun main(args: Array<String>) {
    App()
}
